import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import ClientProvider from "./_components/ClientProvider";
import { CartProvider } from "./_context/CartContex";
const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <ClientProvider>
            <Header />
            {children}
          </ClientProvider>
        </CartProvider>
      </body>
    </html>
  );
}
